#!/bin/bash
set -ex
echo "Installing libdepbo.so.0.6.74"
{
	pushd /opt
	cp /tmp/cache/depbo-tools-0.6.74-linux-64bit.tgz .
	tar xvfz depbo-tools-0.6.74-linux-64bit.tgz && rm depbo-tools-0.6.74-linux-64bit.tgz
	for i in depbo-tools-0.6.74/bin/*; do ln -s $(pwd)/depbo-tools-0.6.74/bin/${i##*/} /usr/local/bin; done 
	ln -s $(pwd)/depbo-tools-0.6.74/lib/libdepbo.so.0 /usr/local/lib/
	ldconfig
	popd 
} > /dev/null